AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Naming/FileName:
  Exclude:
      - 'lib/yaml-file-db.rb'

Metrics/AbcSize:
  Max: 65

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false
